# TCL File Generated by Component Editor 15.1
# Wed Oct 19 19:31:38 EDT 2016
# DO NOT MODIFY


# 
# sd_cont "SD Controller" v1.0
#  2016.10.19.19:31:38
# 
# 

# 
# request TCL package from ACDS 15.1
# 
package require -exact qsys 15.1


# 
# module sd_cont
# 
set_module_property DESCRIPTION ""
set_module_property NAME sd_cont
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME "SD Controller"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL sd_cont
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file sd_cont.v VERILOG PATH sd_cont/sd_cont.v TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point slave
# 
add_interface slave avalon end
set_interface_property slave addressUnits WORDS
set_interface_property slave associatedClock clock
set_interface_property slave associatedReset reset
set_interface_property slave bitsPerSymbol 8
set_interface_property slave burstOnBurstBoundariesOnly false
set_interface_property slave burstcountUnits WORDS
set_interface_property slave explicitAddressSpan 0
set_interface_property slave holdTime 0
set_interface_property slave linewrapBursts false
set_interface_property slave maximumPendingReadTransactions 0
set_interface_property slave maximumPendingWriteTransactions 0
set_interface_property slave readLatency 0
set_interface_property slave readWaitTime 1
set_interface_property slave setupTime 0
set_interface_property slave timingUnits Cycles
set_interface_property slave writeWaitTime 0
set_interface_property slave ENABLED true
set_interface_property slave EXPORT_OF ""
set_interface_property slave PORT_NAME_MAP ""
set_interface_property slave CMSIS_SVD_VARIABLES ""
set_interface_property slave SVD_ADDRESS_GROUP ""

add_interface_port slave s_address address Input 8
add_interface_port slave s_read read Input 1
add_interface_port slave s_readdata readdata Output 32
add_interface_port slave s_write write Input 1
add_interface_port slave s_writedata writedata Input 32
add_interface_port slave s_chipselect chipselect Input 1
add_interface_port slave s_waitrequest_n waitrequest_n Output 1
set_interface_assignment slave embeddedsw.configuration.isFlash 0
set_interface_assignment slave embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment slave embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment slave embeddedsw.configuration.isPrintableDevice 0


# 
# connection point master
# 
add_interface master avalon start
set_interface_property master addressUnits SYMBOLS
set_interface_property master associatedClock clock
set_interface_property master associatedReset reset
set_interface_property master bitsPerSymbol 8
set_interface_property master burstOnBurstBoundariesOnly false
set_interface_property master burstcountUnits WORDS
set_interface_property master doStreamReads false
set_interface_property master doStreamWrites false
set_interface_property master holdTime 0
set_interface_property master linewrapBursts false
set_interface_property master maximumPendingReadTransactions 0
set_interface_property master maximumPendingWriteTransactions 0
set_interface_property master readLatency 0
set_interface_property master readWaitTime 1
set_interface_property master setupTime 0
set_interface_property master timingUnits Cycles
set_interface_property master writeWaitTime 0
set_interface_property master ENABLED true
set_interface_property master EXPORT_OF ""
set_interface_property master PORT_NAME_MAP ""
set_interface_property master CMSIS_SVD_VARIABLES ""
set_interface_property master SVD_ADDRESS_GROUP ""

add_interface_port master m_address address Output 32
add_interface_port master m_read read Output 1
add_interface_port master m_readdata readdata Input 32
add_interface_port master m_write write Output 1
add_interface_port master m_writedata writedata Output 32
add_interface_port master m_waitrequest_n waitrequest_n Input 1


# 
# connection point sd
# 
add_interface sd conduit end
set_interface_property sd associatedClock clock
set_interface_property sd associatedReset reset
set_interface_property sd ENABLED true
set_interface_property sd EXPORT_OF ""
set_interface_property sd PORT_NAME_MAP ""
set_interface_property sd CMSIS_SVD_VARIABLES ""
set_interface_property sd SVD_ADDRESS_GROUP ""

add_interface_port sd sd_clk sd_clk Output 1
add_interface_port sd sd_cmd sd_cmd Bidir 1
add_interface_port sd sd_dat sd_dat Bidir 4


# 
# connection point sd_clk
# 
add_interface sd_clk clock end
set_interface_property sd_clk clockRate 0
set_interface_property sd_clk ENABLED true
set_interface_property sd_clk EXPORT_OF ""
set_interface_property sd_clk PORT_NAME_MAP ""
set_interface_property sd_clk CMSIS_SVD_VARIABLES ""
set_interface_property sd_clk SVD_ADDRESS_GROUP ""

add_interface_port sd_clk sd_pll_clk clk Input 1

